### test de GET
GET http://localhost:3000/users/


### create
POST http://localhost:3000/register/
Content-Type: application/json

{
   "name": "name",
      "email": "email",
      "password" : "password",
      "age" : "age"
}